# Generated by Django 5.1.15 on 2026-01-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipopagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopago',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
